name: Mend Reachability CLI Scan (Windows)

on: workflow_dispatch

jobs:
  build-and-mend-scan:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["12.x"]

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --ignore-scripts

    - name: Mend CLI Download
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas.whitesourcesoftware.com
      run: |
        echo '=== Downloading Mend CLI =='
        curl https://downloads.mend.io/cli/windows_amd64/mend.exe -o mend.exe
        echo '=== Mend CLI version: ==='
        .\mend.exe version

    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas.whitesourcesoftware.com
      run: |
        echo '=== Running Scan ==='
        .\mend.exe dep -u -r
      continue-on-error: true

    - name: Mend CLI Logs
      run: cat ~/.mend/logs/sca/*.log
      continue-on-error: true
